tasks:
  - name: Kidneys segmentation
    key: KIDNEYS_SEGMENTATION
    description: The kidneys are two bean-shaped organs found in vertebrates.
      They are located on the left and right in the retroperitoneal space, and in adult
      humans are about 11 centimetres (4.3 in) in length. They receive blood from the paired
      renal arteries; blood exits into the paired renal veins. Each kidney is attached to a ureter,
      a tube that carries excreted urine to the bladder.
    label_examples: [assets/img/example_1.png, assets/img/example_2.png]
    image_path: assets/icon/kidneys_dataset_icon.svg
    tags:
        - name: Left Kidney
          key: LEFT_KIDNEY
          tools:
              - RECTANGLE
        - name: Right Kidney
          key: RIGHT_KIDNEY
          tools:
              - RECTANGLE

  - name: Find nodules
    key: FIND_NODULES
    image_path: assets/icon/lungs_dataset_icon.svg
    tags:
        - name: Nodule
          key: NODULE
          tools:
              - BRUSH

  - name: Find narrowings in Veins
    key: FIND_NARROWINGS
    image_path: assets/icon/heart_dataset_icon.svg
    tags:
        - name: Narrowing (region)
          key: NARROWING
          tools:
              - BRUSH
        - name: Narrowing (lenghtwise)
          key: NARROWING_LENGHTWISE
          tools:
              - CHAIN
        - name: Narrowing (across)
          key: NARROWING_ACROSS
          tools:
              - CHAIN

  - name: Find middle of the Spine
    key: FIND_MIDDLE_OF_THE_SPINE
    image_path: assets/icon/lungs_dataset_icon.svg
    tags:
        - name: Middle of the Spine
          key: MIDDLE_OF_THE_SPINE
          tools:
              - POINT

datasets:
  - name: Kidneys
    key: KIDNEYS
    tasks:
      - KIDNEYS_SEGMENTATION

  - name: Lungs
    key: LUNGS
    tasks:
      - FIND_NODULES
      - FIND_MIDDLE_OF_THE_SPINE

  - name: Heart
    key: HEART
    tasks:
      - FIND_NARROWINGS
